title: Thema
term: Topic
description: >
  Das Thema ist ein Ereignis in der Welt zu dem Berichterstattung geplant ist und das von einem Autor in einem Hinweis verarbeitet wird. 
tags:
  - Werteinheit
  - dpa
  - Hinweis 
synonyms:
  - Topic  
  