title: Passiert Filter
term: passesfilter
description: >
  Vorläufig: Passiert Filter ist eine Aktivität, die ausgelöst wird wenn eine Werteinheit durch einen Filter passt.
tags:
  - Werteinheit
  - Filter
  - Akteur 
  - Publizieren
  - Aktion

synonyms:
  - Treffer
  
  