/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CdkTagList {
    /**
    * The type
    */
    'tags': any[];
  }
  interface CdkTagListAttributes extends StencilHTMLAttributes {
    /**
    * The type
    */
    'tags'?: any[];
  }

  interface CdkTag {
    /**
    * The text
    */
    'text': string;
    /**
    * The type
    */
    'type': string;
  }
  interface CdkTagAttributes extends StencilHTMLAttributes {
    /**
    * The text
    */
    'text'?: string;
    /**
    * The type
    */
    'type'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CdkTagList': Components.CdkTagList;
    'CdkTag': Components.CdkTag;
  }

  interface StencilIntrinsicElements {
    'cdk-tag-list': Components.CdkTagListAttributes;
    'cdk-tag': Components.CdkTagAttributes;
  }


  interface HTMLCdkTagListElement extends Components.CdkTagList, HTMLStencilElement {}
  var HTMLCdkTagListElement: {
    prototype: HTMLCdkTagListElement;
    new (): HTMLCdkTagListElement;
  };

  interface HTMLCdkTagElement extends Components.CdkTag, HTMLStencilElement {}
  var HTMLCdkTagElement: {
    prototype: HTMLCdkTagElement;
    new (): HTMLCdkTagElement;
  };

  interface HTMLElementTagNameMap {
    'cdk-tag-list': HTMLCdkTagListElement
    'cdk-tag': HTMLCdkTagElement
  }

  interface ElementTagNameMap {
    'cdk-tag-list': HTMLCdkTagListElement;
    'cdk-tag': HTMLCdkTagElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
