version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18  
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-central-1)
      - REPOSITORY_URI=960057802448.dkr.ecr.eu-central-1.amazonaws.com/design-kit
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Check that the docker daemon is running...
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - env
      - chmod -R ugoa+rwX /codebuild/output
      - export AWS_REGION=eu-central-1
  post_build:
    commands:
      - echo Building the Docker image...
      - docker build -t design-kit .
      - docker tag design-kit:latest $REPOSITORY_URI:latest
      - docker tag design-kit:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
cache:
  paths:

