title: Publizieren
term: Publish
description: >
  Publizieren ist eine Aktion eines Akteurs. Eine Person, ein Team oder eine Organisation veröffentlicht eine Werteinheit.
tags:
  - Werteinheit
  - Aktivität
  - Akteur 

synonyms:
  - Einstellen
  - Veröffentlichen 
  - Senden 
  