title: Foto
description: >
  Foto ist eine journalistische Werteinheit der dpa oder anderer Anbieter. Foto ist ein Inhalt, der über das Medienformat Bild typisiert ist.
term: picture
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt
synonyms:
  - Bild
  - media object