custom:
  synonyms:
    - Content
    - news item
    - media object
    - Medienobjekt
  term: NewsItem
description:
  "Ein Nachrichtenstück ist eine Sammlung von Werteinheiten und auch selbst
  eine journalistische Werteinheit. \n"
tags:
  - dpa
  - Inhalt
  - Klassifizierung
  - Werteinheit
title: Nachrichtenstück
