title: Assistent
description: >
  Ein Assistent ist eine Software Programm mit dem Personen zusammenarbeiten.
term: assistent
tags:
  - impl:wip
  - Akteur
  - dpa
synonyms:
  - Bot
  - Helferlein
  - Script