title: Teilen
term: Share
description: >
  Teilen ist eine Aktion eines Akteurs. Eine Person, ein Team oder eine Organisation weist einen Adressaten auf eine oder mehrere Werteinheiten hin.

tags:
  - Werteinheit
  - Aktivität
  - Akteur
  

synonyms:
  - Hinweisen
  - Weiterleiten 
 
  