title: Nachrichtenstück
term: news item
description: >
  Ein Nachrichtenstück ist eine Sammlung von Werteinheiten und auch selbst eine journalistische Werteinheit. 
tags:
  - dpa
  - Inhalt
  - Klassifizierung
  - Werteinheit
synonyms:
  - Content 
  - news item 
  - media object 
  - Medienobjekt