custom:
  synonyms:
    - Team in einem Unternehmen
    - dpa-Ressort
    - Quelle
    - Akteur
  term: team
description: |
  Ein Team beschreibt eine Gruppe von Akteuren.
tags:
  - Akteur
  - dpa
title: Team
