# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    filters:
      branches:
        only: master
    docker:
      # specify the version you desire here
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/design-kit

    steps:
      - checkout

      - run: yarn install

      - run: yarn run docs:build

      - run: 'git config --global user.email circleci@circleci'
      - run: 'git config --global user.name CircleCI'
      - run: yarn run deploy