custom:
  synonyms: null
description: |
  Die Implementierungstiefe ermöglicht der Leserin eine  schnelle Einschätzung über Umfang und Fortschritt der Inhalte im Design Kit
tags:
  - meta
title: Implementierungstiefe
