title: Text
description: >
  Text ist eine journalistische  *Werteinheit*  der dpa oder anderer Anbieter. Text ist ein Inhalt, der über das Medienformat Text typisiert ist.
term: text
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt/Material
synonyms:
  - Artikel
  - Meldung
  - media object