custom:
  synonyms: null
  term: Activity
description:
  "Die Einf체hrung bietet einen Einstieg in das Konzept der Aktivit채ten.
  \n"
tags:
  - dpa
  - Grammatik und Vokabular
  - Akteur
  - Werteinheiten
  - Publizieren
  - Teilen
  - Einalden
title: Einf체hrung in das Konzept der Aktivit채ten
