title: Einf체hrung in das Konzept der Aktivit채ten
term: Activity
description: >
  Die Einf체hrung bietet einen Einstieg in das Konzept der Aktivit채ten. 
tags:
  - dpa
  - Grammatik und Vokabular
  - Akteur
  - Werteinheiten
  - Publizieren
  - Teilen
  - Einalden
  
synonyms:

   
  