custom:
  synonyms:
    - Bot
    - Helferlein
    - Script
  term: assistent
description: |
  Ein Assistent ist eine Software Programm mit dem Personen zusammenarbeiten.
tags:
  - impl:wip
  - Akteur
  - dpa
title: Assistent
