title: Video
description: >
  Video ist eine journalistische Werteinheit der dpa oder anderer Anbieter. Video ist ein Inhalt, der über das Medienformat Video typisiert ist.
term: Video
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt
synonyms:
  - Bewegtbild