title: Fotostrecke
description: >
  Die Fotostrecke ist eine Sammlung von Inhalten typisiert als Medienformat Foto. Sie finden Verwendung in dpa-agenda und dpa-news
term: Foto aktuell, Foto Archiv
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt
synonyms:
  - Bildersammlung
  - Leuchttisch