custom:
  synonyms:
    - Ordner
  term: Folder
description:
  "Die Mappe ist ein individualisierter, gemeinsamer Arbeitsraum für Kollaboration.
  \n"
tags:
  - Werteinheit
  - dpa
  - Liste
  - Kollaboration
title: Mappe
