title: Mappe
term: Folder
description: >
  Die Mappe ist ein individualisierter, gemeinsamer Arbeitsraum für Kollaboration. 
tags:
  - Werteinheit
  - dpa
  - Liste
  - Kollaboration 
synonyms:
  - Ordner  
  