title: Klassifizierung
description: >
  Die Klassifizierung transportiert Stichworte, Geostichworte, Prioritäten, Ressorts in Form von Tags. Tags können seitens der dpa vorgegebene Begriffe, aber auch vom Nutzer freigewählte Begriffe sein.
term: Classification
tags:
  - Klassifizierung
  - dpa
  - Zu-Eigen-Machen
synonyms:
  - Stichworte
  - Geo-Stichworte
  - Meta-Daten