custom:
  synonyms:
    - Hinweisen
    - Weiterleiten
  term: Share
description: |
  Teilen beschreibt das Hinweisen eines Adressanten auf eine oder mehrere Werteinheiten.
tags:
  - impl:draft
  - Werteinheit
  - Aktivität
  - Akteur
title: Teilen
