custom:
  synonyms:
    - Infografik
    - dpa-Grafik
  term: infographic
description: |
  Grafik ist eine journalistische Werteinheit der dpa oder anderer Anbieter. Grafik ist ein Inhalt, der über das Medienformat Grafik typisiert ist.
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt
title: Grafik
