title: Grafik
description: >
  Grafik ist eine journalistische Werteinheit der dpa oder anderer Anbieter. Grafik ist ein Inhalt, der über das Medienformat Grafik typisiert ist.
term: Grafik
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt
synonyms:
  - Infografik  
  - dpa-Grafik