custom:
  synonyms:
    - Bild
    - media object
  term: picture
description: |
  Foto ist eine journalistische Werteinheit der dpa oder anderer Anbieter. Foto ist ein Inhalt, der über das Medienformat Bild typisiert ist.
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt
title: Foto
