custom:
  synonyms:
    - Artikel
    - Meldung
    - media object
  term: text
description: |
  Text ist eine journalistische Werteinheit der dpa oder anderer Anbieter. Text ist ein Inhalt, der über das Medienformat Text typisiert ist.
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt/Material
title: Text
