custom:
  synonyms:
    - Bildersammlung
    - Leuchttisch
    - Foto aktuell
    - Foto Archiv
  term: picturecollection
description: |
  Die Fotostrecke ist eine Sammlung von Inhalten typisiert als Medienformat Foto. Sie finden Verwendung in dpa-agenda und dpa-news
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt
title: Fotostrecke
