custom:
  synonyms:
    - Planung
  term: Coverage
description: |
  Berichterstattung ist die Summe aller gesendeten und geplanten Inhalte der dpa oder anderer Anbieter zu einem bestimmten Thema oder Termin.
tags:
  - impl:japan
title: Berichterstattung
