title: Grammatik und Vokabular
term: vocabulary and grammar
description: >
  F체r Aktivit채ten gibt es ein spezifisches Vokabular und eine darauf aufbauende Grammatik. Aktivit채ten werden so schematisch darstellbar.
tags:
  - dpa
  - Aktivit채ten
  
synonyms:
  - Regeln 
  