title: Grammatik und Vokabular
term: vocabulary and grammar
description: >
  Aktivitäten lassen sich mit Hilfe eines speziellen Vokabulars und einer Grammatik schematisch beschreiben.
tags:
  - dpa
  - Aktivitäten
  - Akteur
  - Publizieren
  - Teilen
  - Einladen
  
synonyms:
  - Regeln 
  