custom:
  synonyms: null
description: |
  Die Ausbaustufen beschreiben den Fortschritt in der Arbeitsbereichen Dokumentation, visuelle Gestaltung und technische Implementierung
tags:
  - meta
title: Ausbaustufen
