custom:
  synonyms:
    - Topic
  term: Topic
description:
  "Das Thema ist ein Ereignis in der Welt zu dem Berichterstattung geplant
  ist und das von einem Autor in einem Hinweis verarbeitet wird. \n"
tags:
  - Werteinheit
  - dpa
  - Hinweis
title: Thema
