custom:
  synonyms:
    - Regeln
  term: vocabulary and grammar
description: |
  Aktivitäten lassen sich mit Hilfe eines speziellen Vokabulars und einer Grammatik schematisch beschreiben.
tags:
  - dpa
  - Aktivitäten
  - Akteur
  - Publizieren
  - Teilen
  - Einladen
title: Grammatik und Vokabular
