title: Inhalt
description: >
  Inhalt ist eine journalistische  *Werteinheit*  der dpa oder anderer Anbieter.
term: Content
tags:
  - Werteinheit
  - dpa
  - Marktplatz
  - impl:outdated
synonyms:
  - Medienobjekt
  - Material
  - Content
  - media object