custom:
  synonyms:
    - Medienobjekt
    - Material
    - Content
    - media object
  term: Content
description: |
  Inhalt ist eine journalistische Werteinheit der dpa oder anderer Anbieter.
tags:
  - Werteinheit
  - dpa
  - Marktplatz
title: Inhalt
