custom:
  synonyms:
    - Kundin
    - User
    - Akteur
  term: User
description: |
  Der Nutzer ist eine Person, die  dpa- und Fremdtools nutzt. Der Nutzer ist Marktplatz-Teilnehmer.
tags:
  - Akteur
  - dpa
title: Nutzer
