custom:
  synonyms: null
  term: Update
description: |
  Aktualisieren beschreibt eine unkritische Änderungen oder Ergänzung zu einer Werteinheit
tags:
  - impl:wip
  - Aktivität
  - Aktion
title: Aktualisieren
