title: Audio
description: >
  Audio ist eine journalistische Werteinheit der dpa oder anderer Anbieter. Audio ist ein Inhalt, der über das Medienformat Audio typisiert ist.
term: Audio
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt
synonyms:
  - O-Ton
  - Hörstück
  - Korri-Talk