custom:
  synonyms:
    - O-Ton
    - Hörstück
    - Korri-Talk
  term: Audio
description: |
  Audio ist eine journalistische Werteinheit der dpa oder anderer Anbieter. Audio ist ein Inhalt, der über das Medienformat Audio typisiert ist.
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt
title: Audio
