title: Publizieren
term: Publish
description: >
  Publizieren beschreibt die Aktion der erstmaligen Veröffentlichung einer Werteinheit.
tags:
  - impl:wip
  - Aktivität
  - Aktion

synonyms:
  - Einstellen
  - Veröffentlichen 
  - Senden 
  