custom:
  synonyms:
    - Einstellen
    - Veröffentlichen
    - Senden
  term: Publish
description: |
  Publizieren beschreibt die Aktion der erstmaligen Veröffentlichung einer Werteinheit.
tags:
  - impl:wip
  - Aktivität
  - Aktion
title: Publizieren
