title: Klassifizierung
description: >
  Tags transportieren Stichworte, Geostichworte, Prioritäten, Ressorts, die zusammen die *Klassifizierung* von dpa-Inhalten bilden. Tags können seitens der dpa vorgegebene Begriffe, aber auch vom Nutzer freigewählte Begriffe sein.
term: Klassifizierung
tags:
  - Klassifizierung
  - dpa
  - Zu-Eigen-Machen
synonyms:
  - Stichworte
  - Geo-Stichworte
  - Meta-Daten