custom:
  synonyms:
    - Termin
    - Thema
    - Agenda-Eintrag
  term: notice
description: |
  Ein Hinweis ist eine Sammlung von Werteinheiten: Autor, Klassifizierung, Termin / Thema, Berichterstattung und auch selbst eine Werteinheit.
tags:
  - dpa
  - Termin
  - Thema
  - Klassifizierung
  - Werteinheit
title: Hinweis
