title: Bild
description: >
  Bild ist eine journalistische Werteinheit der dpa oder anderer Anbieter. Bild ist ein Inhalt, der über das Medienformat Bild typisiert ist.
term: Bild
tags:
  - Werteinheit
  - dpa
  - Medienformat
  - Inhalt
synonyms:
  - Foto  
  - media object