title: Einladen
term: Invite
description: >
  Einladen ist eine Aktion eines Akteurs. Eine Person, ein Team oder eine Organisation lädt einen oder mehrere Akteure zur Kollaboration ein. 

tags:

  - Aktivität
  - Akteur
  - Kollaboration
